//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


namespace AnimusClient.AnimusClientSDK {

public class _GoString_ : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal _GoString_(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(_GoString_ obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~_GoString_() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          animus_client_sdkPINVOKE.delete__GoString_(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string p {
    set {
      animus_client_sdkPINVOKE._GoString__p_set(swigCPtr, value);
    } 
    get {
      string ret = animus_client_sdkPINVOKE._GoString__p_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_ptrdiff_t n {
    set {
      animus_client_sdkPINVOKE._GoString__n_set(swigCPtr, SWIGTYPE_p_ptrdiff_t.getCPtr(value));
      if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_ptrdiff_t ret = new SWIGTYPE_p_ptrdiff_t(animus_client_sdkPINVOKE._GoString__n_get(swigCPtr), true);
      if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public _GoString_() : this(animus_client_sdkPINVOKE.new__GoString_(), true) {
  }

}
}
