//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


namespace AnimusClient.AnimusClientSDK {

class animus_client_sdkPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="SWIGRegisterExceptionCallbacks_animus_client_sdk")]
    public static extern void SWIGRegisterExceptionCallbacks_animus_client_sdk(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_animus_client_sdk")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_animus_client_sdk(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_animus_client_sdk(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_animus_client_sdk(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(animus_client_sdkPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(animus_client_sdkPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="SWIGRegisterStringCallback_animus_client_sdk")]
    public static extern void SWIGRegisterStringCallback_animus_client_sdk(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_animus_client_sdk(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static animus_client_sdkPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_cdata")]
  public static extern global::System.IntPtr cdata(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_memmove")]
  public static extern void memmove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp__GoString__p_set")]
  public static extern void _GoString__p_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp__GoString__p_get")]
  public static extern string _GoString__p_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp__GoString__n_set")]
  public static extern void _GoString__n_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp__GoString__n_get")]
  public static extern global::System.IntPtr _GoString__n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_new__GoString_")]
  public static extern global::System.IntPtr new__GoString_();

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_delete__GoString_")]
  public static extern void delete__GoString_(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_ProtoMessageC_len_set")]
  public static extern void ProtoMessageC_len_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_ProtoMessageC_len_get")]
  public static extern uint ProtoMessageC_len_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_ProtoMessageC_data_set")]
  public static extern void ProtoMessageC_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_ProtoMessageC_data_get")]
  public static extern global::System.IntPtr ProtoMessageC_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_new_ProtoMessageC")]
  public static extern global::System.IntPtr new_ProtoMessageC();

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_delete_ProtoMessageC")]
  public static extern void delete_ProtoMessageC(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoInterface_t_set")]
  public static extern void GoInterface_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoInterface_t_get")]
  public static extern global::System.IntPtr GoInterface_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoInterface_v_set")]
  public static extern void GoInterface_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoInterface_v_get")]
  public static extern global::System.IntPtr GoInterface_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_new_GoInterface")]
  public static extern global::System.IntPtr new_GoInterface();

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_delete_GoInterface")]
  public static extern void delete_GoInterface(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoSlice_data_set")]
  public static extern void GoSlice_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoSlice_data_get")]
  public static extern global::System.IntPtr GoSlice_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoSlice_len_set")]
  public static extern void GoSlice_len_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoSlice_len_get")]
  public static extern long GoSlice_len_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoSlice_cap_set")]
  public static extern void GoSlice_cap_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GoSlice_cap_get")]
  public static extern long GoSlice_cap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_new_GoSlice")]
  public static extern global::System.IntPtr new_GoSlice();

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_delete_GoSlice")]
  public static extern void delete_GoSlice(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_VersionGo")]
  public static extern string VersionGo();

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_SetupGo")]
  public static extern global::System.IntPtr SetupGo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_LoginUserGo")]
  public static extern global::System.IntPtr LoginUserGo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GetRobotsGo")]
  public static extern global::System.IntPtr GetRobotsGo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_ConnectGo")]
  public static extern global::System.IntPtr ConnectGo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_OpenModalityGo")]
  public static extern global::System.IntPtr OpenModalityGo(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_SetModalityGo")]
  public static extern global::System.IntPtr SetModalityGo(string jarg1, string jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GetModalityGo")]
  public static extern global::System.IntPtr GetModalityGo(string jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_CloseModalityGo")]
  public static extern global::System.IntPtr CloseModalityGo(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_DisconnectGo")]
  public static extern global::System.IntPtr DisconnectGo(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_CloseClientInterfaceGo")]
  public static extern void CloseClientInterfaceGo();

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_Setup")]
  public static extern global::System.IntPtr Setup(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_LoginUser")]
  public static extern global::System.IntPtr LoginUser(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GetRobots")]
  public static extern global::System.IntPtr GetRobots(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_Connect")]
  public static extern global::System.IntPtr Connect(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_OpenModality")]
  public static extern global::System.IntPtr OpenModality(string jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_SetModality")]
  public static extern global::System.IntPtr SetModality(string jarg1, string jarg2, int jarg3, string jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_GetModality")]
  public static extern global::System.IntPtr GetModality(string jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_CloseModality")]
  public static extern global::System.IntPtr CloseModality(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("animus_client_sdk", EntryPoint="CSharp_Disconnect")]
  public static extern global::System.IntPtr Disconnect(string jarg1);
}
}
