//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


namespace AnimusClient.AnimusClientSDK {

public class animus_client_sdk {
  public static SWIGTYPE_p_SWIGCDATA cdata(SWIGTYPE_p_void ptr, int nelements) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.cdata(SWIGTYPE_p_void.getCPtr(ptr), nelements), true);
    return ret;
  }

  public static void memmove(SWIGTYPE_p_void data, SWIGTYPE_p_void indata, int inlen) {
    animus_client_sdkPINVOKE.memmove(SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_void.getCPtr(indata), inlen);
  }

  public static string VersionGo() {
    string ret = animus_client_sdkPINVOKE.VersionGo();
    return ret;
  }

  public static ProtoMessageC SetupGo(ProtoMessageC p0) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.SetupGo(ProtoMessageC.getCPtr(p0)), true);
    if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ProtoMessageC LoginUserGo(ProtoMessageC p0) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.LoginUserGo(ProtoMessageC.getCPtr(p0)), true);
    if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ProtoMessageC GetRobotsGo(ProtoMessageC p0) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.GetRobotsGo(ProtoMessageC.getCPtr(p0)), true);
    if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ProtoMessageC ConnectGo(ProtoMessageC p0) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.ConnectGo(ProtoMessageC.getCPtr(p0)), true);
    if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ProtoMessageC OpenModalityGo(string p0, ProtoMessageC p1) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.OpenModalityGo(p0, ProtoMessageC.getCPtr(p1)), true);
    if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ProtoMessageC SetModalityGo(string p0, string p1, int p2, ProtoMessageC p3) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.SetModalityGo(p0, p1, p2, ProtoMessageC.getCPtr(p3)), true);
    if (animus_client_sdkPINVOKE.SWIGPendingException.Pending) throw animus_client_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ProtoMessageC GetModalityGo(string p0, string p1, int p2) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.GetModalityGo(p0, p1, p2), true);
    return ret;
  }

  public static ProtoMessageC CloseModalityGo(string p0, string p1) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.CloseModalityGo(p0, p1), true);
    return ret;
  }

  public static ProtoMessageC DisconnectGo(string p0) {
    ProtoMessageC ret = new ProtoMessageC(animus_client_sdkPINVOKE.DisconnectGo(p0), true);
    return ret;
  }

  public static void CloseClientInterfaceGo() {
    animus_client_sdkPINVOKE.CloseClientInterfaceGo();
  }

  public static SWIGTYPE_p_SWIGCDATA Setup(string p0, int p1) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.Setup(p0, p1), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA LoginUser(string p0, int p1) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.LoginUser(p0, p1), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA GetRobots(string p0, int p1) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.GetRobots(p0, p1), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA Connect(string p0, int p1) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.Connect(p0, p1), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA OpenModality(string p0, string p1, int p2) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.OpenModality(p0, p1, p2), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA SetModality(string p0, string p1, int p2, string p3, int p4) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.SetModality(p0, p1, p2, p3, p4), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA GetModality(string p0, string p1, int p2) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.GetModality(p0, p1, p2), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA CloseModality(string p0, string p1) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.CloseModality(p0, p1), true);
    return ret;
  }

  public static SWIGTYPE_p_SWIGCDATA Disconnect(string p0) {
    SWIGTYPE_p_SWIGCDATA ret = new SWIGTYPE_p_SWIGCDATA(animus_client_sdkPINVOKE.Disconnect(p0), true);
    return ret;
  }

}
}
