//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

 
using System;

namespace AnimusClient.AnimusClientSDK {

public class ProtoMessageC : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ProtoMessageC(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ProtoMessageC obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ProtoMessageC() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          animus_client_sdkPINVOKE.delete_ProtoMessageC(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint len {
    set {
      animus_client_sdkPINVOKE.ProtoMessageC_len_set(swigCPtr, value);
    } 
    get {
      uint ret = animus_client_sdkPINVOKE.ProtoMessageC_len_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void data {
    set {
      animus_client_sdkPINVOKE.ProtoMessageC_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = animus_client_sdkPINVOKE.ProtoMessageC_data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public unsafe byte[] GetBytes()
  {
    global::System.IntPtr cPtr = animus_client_sdkPINVOKE.ProtoMessageC_data_get(swigCPtr);
    if (cPtr == global::System.IntPtr.Zero)
    {
      return null;
    }
    
    Span<byte> byteArray = new Span<byte>(cPtr.ToPointer(), (int)this.len);
    return byteArray.ToArray();
  }

  public ProtoMessageC() : this(animus_client_sdkPINVOKE.new_ProtoMessageC(), true) {
  }

}
}
