// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: animus_robot_sdk.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Animus.RobotSDK {

  /// <summary>Holder for reflection information generated from animus_robot_sdk.proto</summary>
  public static partial class AnimusRobotSdkReflection {

    #region Descriptor
    /// <summary>File descriptor for animus_robot_sdk.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnimusRobotSdkReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZhbmltdXNfcm9ib3Rfc2RrLnByb3RvEhBhbmltdXMucm9ib3Rfc2RrGhJh",
            "bmltdXNfcm9ib3QucHJvdG8aE2FuaW11c19jb21tb24ucHJvdG8iMAoPU2V0",
            "dXBSb2JvdFByb3RvEg4KBmxvZ0RpchgBIAEoCRINCgVEZWJ1ZxgCIAEoCCJj",
            "ChRTdGFydFJvYm90Q29tbXNQcm90bxISCgpzdGFydExvY2FsGAEgASgIEhMK",
            "C3N0YXJ0UmVtb3RlGAIgASgIEiIKBXJvYm90GAMgASgLMhMuYW5pbXVzLnJv",
            "Ym90LlJvYm90IlsKEFJvYm90Q29uZmlnUHJvdG8SIgoFcm9ib3QYASABKAsy",
            "Ey5hbmltdXMucm9ib3QuUm9ib3QSIwoFZXJyb3IYAiABKAsyFC5hbmltdXMu",
            "Y29tbW9uLkVycm9yIisKCVRlc3RSb2JvdBIQCghyb2JvdF9pZBgBIAEoCRIM",
            "CgRtYWtlGAIgASgJImgKEUNoYW5nZUNvbmZpZ1Byb3RvEioKBXJvYm90GAMg",
            "ASgLMhsuYW5pbXVzLnJvYm90X3Nkay5UZXN0Um9ib3QSEgoKc3RhcnRMb2Nh",
            "bBgBIAEoCBITCgtzdGFydFJlbW90ZRgCIAEoCEKDAQogY29tLmN5YmVyc2Vs",
            "dmVzLmFuaW11cy5yb2JvdF9zZGtCE0FuaW11c1JvYm90U0RLUHJvdG9IAVol",
            "Z2l0aHViLmNvbS9DeWJlcnNlbHZlcy9BbmltdXNNZXNzYWdlc6ICDkFuaW11",
            "c1JvYm90U0RLqgIPQW5pbXVzLlJvYm90U0RLYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Animus.RobotProto.AnimusRobotReflection.Descriptor, global::Animus.Common.AnimusCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Animus.RobotSDK.SetupRobotProto), global::Animus.RobotSDK.SetupRobotProto.Parser, new[]{ "LogDir", "Debug" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Animus.RobotSDK.StartRobotCommsProto), global::Animus.RobotSDK.StartRobotCommsProto.Parser, new[]{ "StartLocal", "StartRemote", "Robot" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Animus.RobotSDK.RobotConfigProto), global::Animus.RobotSDK.RobotConfigProto.Parser, new[]{ "Robot", "Error" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Animus.RobotSDK.TestRobot), global::Animus.RobotSDK.TestRobot.Parser, new[]{ "RobotId", "Make" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Animus.RobotSDK.ChangeConfigProto), global::Animus.RobotSDK.ChangeConfigProto.Parser, new[]{ "Robot", "StartLocal", "StartRemote" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SetupRobotProto : pb::IMessage<SetupRobotProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetupRobotProto> _parser = new pb::MessageParser<SetupRobotProto>(() => new SetupRobotProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetupRobotProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Animus.RobotSDK.AnimusRobotSdkReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetupRobotProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetupRobotProto(SetupRobotProto other) : this() {
      logDir_ = other.logDir_;
      debug_ = other.debug_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetupRobotProto Clone() {
      return new SetupRobotProto(this);
    }

    /// <summary>Field number for the "logDir" field.</summary>
    public const int LogDirFieldNumber = 1;
    private string logDir_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LogDir {
      get { return logDir_; }
      set {
        logDir_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Debug" field.</summary>
    public const int DebugFieldNumber = 2;
    private bool debug_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Debug {
      get { return debug_; }
      set {
        debug_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetupRobotProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetupRobotProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LogDir != other.LogDir) return false;
      if (Debug != other.Debug) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LogDir.Length != 0) hash ^= LogDir.GetHashCode();
      if (Debug != false) hash ^= Debug.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LogDir.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LogDir);
      }
      if (Debug != false) {
        output.WriteRawTag(16);
        output.WriteBool(Debug);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LogDir.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LogDir);
      }
      if (Debug != false) {
        output.WriteRawTag(16);
        output.WriteBool(Debug);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LogDir.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LogDir);
      }
      if (Debug != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetupRobotProto other) {
      if (other == null) {
        return;
      }
      if (other.LogDir.Length != 0) {
        LogDir = other.LogDir;
      }
      if (other.Debug != false) {
        Debug = other.Debug;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LogDir = input.ReadString();
            break;
          }
          case 16: {
            Debug = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LogDir = input.ReadString();
            break;
          }
          case 16: {
            Debug = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StartRobotCommsProto : pb::IMessage<StartRobotCommsProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StartRobotCommsProto> _parser = new pb::MessageParser<StartRobotCommsProto>(() => new StartRobotCommsProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartRobotCommsProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Animus.RobotSDK.AnimusRobotSdkReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartRobotCommsProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartRobotCommsProto(StartRobotCommsProto other) : this() {
      startLocal_ = other.startLocal_;
      startRemote_ = other.startRemote_;
      robot_ = other.robot_ != null ? other.robot_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartRobotCommsProto Clone() {
      return new StartRobotCommsProto(this);
    }

    /// <summary>Field number for the "startLocal" field.</summary>
    public const int StartLocalFieldNumber = 1;
    private bool startLocal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool StartLocal {
      get { return startLocal_; }
      set {
        startLocal_ = value;
      }
    }

    /// <summary>Field number for the "startRemote" field.</summary>
    public const int StartRemoteFieldNumber = 2;
    private bool startRemote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool StartRemote {
      get { return startRemote_; }
      set {
        startRemote_ = value;
      }
    }

    /// <summary>Field number for the "robot" field.</summary>
    public const int RobotFieldNumber = 3;
    private global::Animus.RobotProto.Robot robot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Animus.RobotProto.Robot Robot {
      get { return robot_; }
      set {
        robot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartRobotCommsProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartRobotCommsProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartLocal != other.StartLocal) return false;
      if (StartRemote != other.StartRemote) return false;
      if (!object.Equals(Robot, other.Robot)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StartLocal != false) hash ^= StartLocal.GetHashCode();
      if (StartRemote != false) hash ^= StartRemote.GetHashCode();
      if (robot_ != null) hash ^= Robot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartLocal != false) {
        output.WriteRawTag(8);
        output.WriteBool(StartLocal);
      }
      if (StartRemote != false) {
        output.WriteRawTag(16);
        output.WriteBool(StartRemote);
      }
      if (robot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Robot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartLocal != false) {
        output.WriteRawTag(8);
        output.WriteBool(StartLocal);
      }
      if (StartRemote != false) {
        output.WriteRawTag(16);
        output.WriteBool(StartRemote);
      }
      if (robot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Robot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StartLocal != false) {
        size += 1 + 1;
      }
      if (StartRemote != false) {
        size += 1 + 1;
      }
      if (robot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Robot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartRobotCommsProto other) {
      if (other == null) {
        return;
      }
      if (other.StartLocal != false) {
        StartLocal = other.StartLocal;
      }
      if (other.StartRemote != false) {
        StartRemote = other.StartRemote;
      }
      if (other.robot_ != null) {
        if (robot_ == null) {
          Robot = new global::Animus.RobotProto.Robot();
        }
        Robot.MergeFrom(other.Robot);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartLocal = input.ReadBool();
            break;
          }
          case 16: {
            StartRemote = input.ReadBool();
            break;
          }
          case 26: {
            if (robot_ == null) {
              Robot = new global::Animus.RobotProto.Robot();
            }
            input.ReadMessage(Robot);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartLocal = input.ReadBool();
            break;
          }
          case 16: {
            StartRemote = input.ReadBool();
            break;
          }
          case 26: {
            if (robot_ == null) {
              Robot = new global::Animus.RobotProto.Robot();
            }
            input.ReadMessage(Robot);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RobotConfigProto : pb::IMessage<RobotConfigProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RobotConfigProto> _parser = new pb::MessageParser<RobotConfigProto>(() => new RobotConfigProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RobotConfigProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Animus.RobotSDK.AnimusRobotSdkReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RobotConfigProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RobotConfigProto(RobotConfigProto other) : this() {
      robot_ = other.robot_ != null ? other.robot_.Clone() : null;
      error_ = other.error_ != null ? other.error_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RobotConfigProto Clone() {
      return new RobotConfigProto(this);
    }

    /// <summary>Field number for the "robot" field.</summary>
    public const int RobotFieldNumber = 1;
    private global::Animus.RobotProto.Robot robot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Animus.RobotProto.Robot Robot {
      get { return robot_; }
      set {
        robot_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private global::Animus.Common.Error error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Animus.Common.Error Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RobotConfigProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RobotConfigProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Robot, other.Robot)) return false;
      if (!object.Equals(Error, other.Error)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (robot_ != null) hash ^= Robot.GetHashCode();
      if (error_ != null) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (robot_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Robot);
      }
      if (error_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (robot_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Robot);
      }
      if (error_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (robot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Robot);
      }
      if (error_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RobotConfigProto other) {
      if (other == null) {
        return;
      }
      if (other.robot_ != null) {
        if (robot_ == null) {
          Robot = new global::Animus.RobotProto.Robot();
        }
        Robot.MergeFrom(other.Robot);
      }
      if (other.error_ != null) {
        if (error_ == null) {
          Error = new global::Animus.Common.Error();
        }
        Error.MergeFrom(other.Error);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (robot_ == null) {
              Robot = new global::Animus.RobotProto.Robot();
            }
            input.ReadMessage(Robot);
            break;
          }
          case 18: {
            if (error_ == null) {
              Error = new global::Animus.Common.Error();
            }
            input.ReadMessage(Error);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (robot_ == null) {
              Robot = new global::Animus.RobotProto.Robot();
            }
            input.ReadMessage(Robot);
            break;
          }
          case 18: {
            if (error_ == null) {
              Error = new global::Animus.Common.Error();
            }
            input.ReadMessage(Error);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TestRobot : pb::IMessage<TestRobot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestRobot> _parser = new pb::MessageParser<TestRobot>(() => new TestRobot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestRobot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Animus.RobotSDK.AnimusRobotSdkReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestRobot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestRobot(TestRobot other) : this() {
      robotId_ = other.robotId_;
      make_ = other.make_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestRobot Clone() {
      return new TestRobot(this);
    }

    /// <summary>Field number for the "robot_id" field.</summary>
    public const int RobotIdFieldNumber = 1;
    private string robotId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RobotId {
      get { return robotId_; }
      set {
        robotId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "make" field.</summary>
    public const int MakeFieldNumber = 2;
    private string make_ = "";
    /// <summary>
    ///  string model = 3;
    ///  string name = 4;
    ///  string hardware_hash = 5;
    /////  animus.structs.License license = 6;
    ///  int64 join_date = 7;
    ///  RobotConfig robot_config = 9;
    /////  RobotState  robot_state = 10;
    ///  string CoreVersion = 11;
    ///  string RobotVersion = 12;
    ///  string DriverVersion = 13;
    ///  string DriverLanguage = 14;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Make {
      get { return make_; }
      set {
        make_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestRobot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestRobot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RobotId != other.RobotId) return false;
      if (Make != other.Make) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RobotId.Length != 0) hash ^= RobotId.GetHashCode();
      if (Make.Length != 0) hash ^= Make.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RobotId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RobotId);
      }
      if (Make.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Make);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RobotId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RobotId);
      }
      if (Make.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Make);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RobotId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RobotId);
      }
      if (Make.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Make);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestRobot other) {
      if (other == null) {
        return;
      }
      if (other.RobotId.Length != 0) {
        RobotId = other.RobotId;
      }
      if (other.Make.Length != 0) {
        Make = other.Make;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RobotId = input.ReadString();
            break;
          }
          case 18: {
            Make = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RobotId = input.ReadString();
            break;
          }
          case 18: {
            Make = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChangeConfigProto : pb::IMessage<ChangeConfigProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChangeConfigProto> _parser = new pb::MessageParser<ChangeConfigProto>(() => new ChangeConfigProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChangeConfigProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Animus.RobotSDK.AnimusRobotSdkReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChangeConfigProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChangeConfigProto(ChangeConfigProto other) : this() {
      robot_ = other.robot_ != null ? other.robot_.Clone() : null;
      startLocal_ = other.startLocal_;
      startRemote_ = other.startRemote_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChangeConfigProto Clone() {
      return new ChangeConfigProto(this);
    }

    /// <summary>Field number for the "robot" field.</summary>
    public const int RobotFieldNumber = 3;
    private global::Animus.RobotSDK.TestRobot robot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Animus.RobotSDK.TestRobot Robot {
      get { return robot_; }
      set {
        robot_ = value;
      }
    }

    /// <summary>Field number for the "startLocal" field.</summary>
    public const int StartLocalFieldNumber = 1;
    private bool startLocal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool StartLocal {
      get { return startLocal_; }
      set {
        startLocal_ = value;
      }
    }

    /// <summary>Field number for the "startRemote" field.</summary>
    public const int StartRemoteFieldNumber = 2;
    private bool startRemote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool StartRemote {
      get { return startRemote_; }
      set {
        startRemote_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChangeConfigProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChangeConfigProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Robot, other.Robot)) return false;
      if (StartLocal != other.StartLocal) return false;
      if (StartRemote != other.StartRemote) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (robot_ != null) hash ^= Robot.GetHashCode();
      if (StartLocal != false) hash ^= StartLocal.GetHashCode();
      if (StartRemote != false) hash ^= StartRemote.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartLocal != false) {
        output.WriteRawTag(8);
        output.WriteBool(StartLocal);
      }
      if (StartRemote != false) {
        output.WriteRawTag(16);
        output.WriteBool(StartRemote);
      }
      if (robot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Robot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartLocal != false) {
        output.WriteRawTag(8);
        output.WriteBool(StartLocal);
      }
      if (StartRemote != false) {
        output.WriteRawTag(16);
        output.WriteBool(StartRemote);
      }
      if (robot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Robot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (robot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Robot);
      }
      if (StartLocal != false) {
        size += 1 + 1;
      }
      if (StartRemote != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChangeConfigProto other) {
      if (other == null) {
        return;
      }
      if (other.robot_ != null) {
        if (robot_ == null) {
          Robot = new global::Animus.RobotSDK.TestRobot();
        }
        Robot.MergeFrom(other.Robot);
      }
      if (other.StartLocal != false) {
        StartLocal = other.StartLocal;
      }
      if (other.StartRemote != false) {
        StartRemote = other.StartRemote;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartLocal = input.ReadBool();
            break;
          }
          case 16: {
            StartRemote = input.ReadBool();
            break;
          }
          case 26: {
            if (robot_ == null) {
              Robot = new global::Animus.RobotSDK.TestRobot();
            }
            input.ReadMessage(Robot);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartLocal = input.ReadBool();
            break;
          }
          case 16: {
            StartRemote = input.ReadBool();
            break;
          }
          case 26: {
            if (robot_ == null) {
              Robot = new global::Animus.RobotSDK.TestRobot();
            }
            input.ReadMessage(Robot);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
